const client = window.supabaseClient;
const DEFAULTS = {
  meta:{title:'دعوة زفاف | عمار & فاطمة',description:'دعوة زفاف عمار & فاطمة ❤️ الثلاثاء 6 أكتوبر 2026 الساعة 6:00 مساءً بقاعة مارشال - أجا - الدقهلية',shareText:'يسعدنا حضوركم ومشاركتنا فرحتنا في أجمل ليلة من ليالينا',socialImage:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85'},
  splash:{openText:'اضغط لفتح الدعوة'},welcome:{eyebrow:'أهلًا وسهلًا بكم',title:'يسعدنا حضوركم',description:'ومشاركتنا فرحتنا في أجمل ليلة من ليالينا'},
  hero:{bismillah:'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ',intro:'يتشرفون بدعوة سيادتكم والعائلة الكريمة لحضور حفل زفاف',dateLabel:'السادس من أكتوبر ٢٠٢٦'},
  couple:{eyebrow:'العروسين',title:'حكاية عمر وفرحة واحدة',subtitle:'بكل حب وفرحة',groomLabel:'العريس',brideLabel:'العروسة',groomName:'عمار',brideName:'فاطمة',story:'واجتمع قلبان على المحبة، وابتدت حكاية جديدة',dateLabel:'٦ أكتوبر ٢٠٢٦ · ٦:٠٠ مساءً',displayNames:'عمار & فاطمة',englishNames:'Ammar & Fatma'},
  verse:{text:'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً',credit:'صدق الله العظيم'},
  families:{title:'عائلات العروسين',groom:{label:'نجل الأول محاسب',name:'عـمـار',familyTitle:'عائلات عبد العال',members:['كابتن / رضا محمد عبد العال','كابتن / محمد رضا عبد العال','كابتن / مصعب رضا عبد العال','الحاج / حسين أحمد حسين (جد العريس)']},bride:{label:'كريمة الثامن الأستاذه',name:'فـاطـمـة',familyTitle:'عائلات الطويل',members:['المرحوم الشيخ / عبد الحميد الطويل','المرحوم / محي الدين عبد الحميد الطويل','الحاج / محمد عبد الحميد الطويل','المهندس / أحمد عبد الحميد الطويل','الحاج / مصطفى عبد الحميد الطويل','المحاسب / عبد الوهاب عبد الحميد الطويل','المهندس / عبد الحميد أحمد عبد الحميد الطويل']}},
  events:[{title:'حنة العريس',dateLabel:'الأحد 4 أكتوبر 2026',location:'أمام منزل والد العريس',description:'',mapQuery:'',mapsUrl:'',startISO:'2026-10-04T18:00:00+03:00',endISO:'2026-10-04T23:00:00+03:00',calendarTitle:'حنة العريس'},{title:'حنة العروسة',dateLabel:'الإثنين 5 أكتوبر 2026',location:'بملعب الغراقة',description:'',mapQuery:'',mapsUrl:'',startISO:'2026-10-05T18:00:00+03:00',endISO:'2026-10-05T23:00:00+03:00',calendarTitle:'حنة العروسة'},{title:'حفل الزفاف',dateLabel:'الثلاثاء 6 أكتوبر 2026 · 6:00 مساءً',location:'بقاعة مارشال - أجا',description:'الدقهلية · جمهورية مصر العربية',mapQuery:'قاعة مارشال - أجا - الدقهلية - مصر',mapsUrl:'',startISO:'2026-10-06T18:00:00+03:00',endISO:'2026-10-06T23:00:00+03:00',calendarTitle:'حفل زفاف عمار وفاطمة'}],
  countdown:{title:'في انتظاركم بكل حب',dateLabel:'الثلاثاء 6 أكتوبر 2026 · الساعة 6:00 مساءً',targetISO:'2026-10-06T18:00:00+03:00',finishedText:'اليوم فرحتنا اكتملت ❤️'},
  closing:{eyebrow:'بكل حب ننتظركم',title:'شرفتمونا ونورتم فرحتنا 🤍',dateLabel:'٦ أكتوبر ٢٠٢٦',timeLabel:'٦:٠٠ مساءً'},
  qr:{title:'احتفظ بالدعوة',help:'امسح الكود لفتح الدعوة مرة أخرى'},media:{musicUrl:'./music.mp3?v=20261002'},
  appearance:{roseGold:'#B76E79',gold:'#D4AF37',cream:'#FFFCF9',softBlush:'#FDF5F6'},features:{musicAutoplay:true,autoScroll:false,petals:true,sectionRail:true,countdown:true,qr:true}
};
let state=structuredClone(DEFAULTS),session=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a;if(a&&typeof a==='object'){const o={...a};if(b&&typeof b==='object')for(const[k,v]of Object.entries(b))o[k]=merge(a[k],v);return o}return b===undefined?a:b}
function get(obj,path){return path.split('.').reduce((a,k)=>a?.[k],obj)}
function set(obj,path,val){const parts=path.split('.');let cur=obj;for(let i=0;i<parts.length-1;i++){if(!cur[parts[i]]||typeof cur[parts[i]]!=='object')cur[parts[i]]={};cur=cur[parts[i]]}cur[parts.at(-1)]=val}
function toast(msg,kind=''){const el=$('#status');el.textContent=msg;el.className='status show '+kind;clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.className='status',3000)}
function bind(){ $$('[data-bind]').forEach(el=>{const p=el.dataset.bind;el.value=get(state,p)??'';el.oninput=()=>set(state,p,el.value)}); $$('[data-bind-bool]').forEach(el=>{const p=el.dataset.bindBool;el.checked=Boolean(get(state,p));el.onchange=()=>set(state,p,el.checked)}) }
function renderMembers(side){const box=side==='groom'?$('#groomMembers'):$('#brideMembers');const p=`families.${side}.members`;box.innerHTML='';(get(state,p)||[]).forEach((v,i)=>{const row=document.createElement('div');row.className='member-row';const input=document.createElement('input');input.value=v;input.oninput=()=>state.families[side].members[i]=input.value;const del=document.createElement('button');del.className='btn btn-danger';del.textContent='حذف';del.onclick=()=>{state.families[side].members.splice(i,1);renderMembers(side);updateStats()};row.append(input,del);box.append(row)});const add=document.createElement('button');add.className='btn';add.textContent='+ إضافة شخص';add.onclick=()=>{state.families[side].members.push('');renderMembers(side);updateStats()};box.append(add)}
function renderEvents(){const root=$('#eventsEditor');root.innerHTML='';state.events.forEach((ev,i)=>{const card=document.createElement('div');card.className='event-card';card.innerHTML=`<div class="row"><div><h2 style="margin:0;font-family:Amiri,serif">المناسبة ${i+1}</h2><div class="muted">يمكنك تعديل الاسم والتاريخ والمكان والخريطة والتقويم.</div></div><button class="btn btn-danger" data-remove>حذف</button></div><div style="height:12px"></div><div class="grid">${field('العنوان','title',ev.title)}${field('التاريخ الظاهر','dateLabel',ev.dateLabel)}${field('المكان','location',ev.location,'full')}${field('الوصف','description',ev.description,'full',true)}${field('بحث Google Maps','mapQuery',ev.mapQuery,'full')}${field('رابط Google Maps','mapsUrl',ev.mapsUrl,'full')}${field('بداية ISO','startISO',ev.startISO)}${field('نهاية ISO','endISO',ev.endISO)}${field('عنوان التقويم','calendarTitle',ev.calendarTitle)}</div>`;card.querySelector('[data-remove]').onclick=()=>{state.events.splice(i,1);renderEvents();updateStats()};card.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;el.oninput=()=>state.events[i][k]=el.value});root.append(card)});updateStats()}
function field(label,key,value,cls='',area=false){return `<div class="field ${cls}"><label>${label}</label>${area?`<textarea data-k="${key}">${esc(value)}</textarea>`:`<input data-k="${key}" value="${esc(value)}">`}</div>`}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function updateStats(){$('#statEvents').textContent=state.events.length;$('#statGroomFamily').textContent=state.families.groom.members.length;$('#statBrideFamily').textContent=state.families.bride.members.length}
function setupTabs(){$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(b=>b.classList.toggle('active',b===btn));$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==btn.dataset.tab));window.scrollTo({top:0,behavior:'smooth'})})}
async function loadState(){const r=await client.from('wedding_settings').select('data,updated_at').eq('id',1).maybeSingle();if(r.error)throw r.error;if(r.data?.data)state=merge(DEFAULTS,r.data.data);return r.data?.updated_at}
async function save(){if(!session)return toast('سجّل الدخول أولاً','bad');const r=await client.from('wedding_settings').upsert({id:1,owner_id:session.user.id,data:state},{onConflict:'id'});if(r.error){console.error(r.error);return toast(r.error.message,'bad')}toast('تم حفظ التعديلات بنجاح ❤️','ok');updateStats()}
async function openApp(){const r=await loadState();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userLabel').textContent=session.user.email||'';bind();renderMembers('groom');renderMembers('bride');renderEvents();setupTabs();if(r) document.title='لوحة التحكم · '+new Date(r).toLocaleString('ar-EG')}
async function boot(){if(!client)return toast('تعذر الاتصال بـ Supabase','bad');const r=await client.auth.getSession();session=r.data.session;if(session)await openApp()}
$('#loginBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return toast('أدخل البريد وكلمة المرور','bad');const r=await client.auth.signInWithPassword({email,password});if(r.error)return toast(r.error.message,'bad');session=r.data.session;await openApp()}
$('#signupBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6)return toast('أدخل بريدًا وكلمة مرور 6 أحرف على الأقل','bad');const r=await client.auth.signUp({email,password});if(r.error)return toast(r.error.message,'bad');toast(r.data.session?'تم إنشاء الحساب':'تم إنشاء الحساب. أكّد البريد الإلكتروني ثم سجّل الدخول.','ok')}
$('#saveBtn').onclick=save;$('#logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};$('#addEventBtn').onclick=()=>{state.events.push({title:'مناسبة جديدة',dateLabel:'',location:'',description:'',mapQuery:'',mapsUrl:'',startISO:'2026-10-07T18:00:00+03:00',endISO:'2026-10-07T23:00:00+03:00',calendarTitle:'مناسبة جديدة'});renderEvents();updateStats()};
boot().catch(e=>{console.error(e);toast('تعذر فتح لوحة التحكم: '+e.message,'bad')});
